name = "MacroEconometrics"
uuid = "3b0be56e-fe13-4819-a73b-716f3628de97"
authors = ["Enrico Wegner"]
version = "1.0.0-DEV"

[deps]
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
